# Generated by Django 5.2.4 on 2025-07-05 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("site_setting", "0002_invitationtemplates_templatecolor_templatefontname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("venue_name", models.CharField(blank=True, max_length=200, null=True)),
                ("google_map_embed_link", models.TextField(blank=True, null=True)),
                ("youtube_embed_link", models.TextField(blank=True, null=True)),
                ("video_message_embed_link", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation_background_music",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="music",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3"]
                            )
                        ],
                    ),
                ),
                ("logo_kh", models.ImageField(blank=True, null=True, upload_to="logo")),
                ("logo_en", models.ImageField(blank=True, null=True, upload_to="logo")),
                (
                    "loading_screen",
                    models.ImageField(
                        blank=True, null=True, upload_to="loading_screen"
                    ),
                ),
                (
                    "event_banner",
                    models.ImageField(blank=True, null=True, upload_to="event_banner"),
                ),
                (
                    "transition_video",
                    models.FileField(
                        blank=True, null=True, upload_to="transition_video"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding"),
                            ("birthday", "Birthday"),
                            ("housewarming", "Housewarming"),
                            ("conferences", "Conferences"),
                            ("seminars", "Seminars"),
                            ("concert", "Concert"),
                            ("retreat", "Retreat"),
                            ("other", "Other"),
                        ],
                        default="wedding",
                        max_length=30,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="site_setting.invitationtemplates",
                    ),
                ),
                (
                    "package_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="site_setting.pricingplan",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events_as_team_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="event_photo"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_photos",
                        to="events.events",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_sponsor_logo"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_sponsors",
                        to="events.events",
                    ),
                ),
            ],
        ),
    ]
