# Generated by Django 5.2.4 on 2025-07-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_agenda_agendadetail_host_hostnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
