# Generated by Django 5.2.4 on 2025-07-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_is_public_alter_events_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='is_public',
            new_name='is_publish',
        ),
    ]
