# Generated by Django 5.2.4 on 2025-07-08 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_is_public_events_is_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('time_text', models.TextField(blank=True, null=True)),
                ('date_text', models.TextField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_texts', to='events.events')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationSubText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_text', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sub_text', to='events.invitationtext')),
            ],
        ),
    ]
