# Generated by Django 5.2.4 on 2025-07-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_invitationtext_invitationsubtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingGiftPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
