# Generated by Django 4.2.23 on 2025-07-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mymodel_options_mymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
