# Generated by Django 5.2.4 on 2025-07-04 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for the font, e.g., 'Roboto', 'Open Sans'.", max_length=100, unique=True)),
                ('font_file', models.FileField(help_text='Upload a font file (TTF, OTF, WOFF, WOFF2).', upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ttf', 'otf', 'woff', 'woff2'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Font',
                'verbose_name_plural': 'Custom Fonts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for the icon, e.g., 'Conference', 'Dinner'.", max_length=100, unique=True)),
                ('svg_code', models.TextField(help_text='Paste the SVG code or image tag for the icon.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(help_text="Add features separated by a comma, e.g., 'Feature1, Feature2, Feature3'")),
                ('purchase_link', models.URLField(blank=True, help_text='Link to purchase the plan', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_profile')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
