# Generated by Django 5.2.4 on 2025-07-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_setting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationTemplates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "basic_decoration_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="basic_decorations_photo"
                    ),
                ),
                (
                    "basic_backgorund_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="basic_background_photo"
                    ),
                ),
                (
                    "standard_cover_video",
                    models.FileField(
                        blank=True, null=True, upload_to="standard_cover_video"
                    ),
                ),
                (
                    "standard_background_video",
                    models.FileField(
                        blank=True, null=True, upload_to="standard_background_video"
                    ),
                ),
                (
                    "package_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="site_setting.pricingplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hex_color_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "invitation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_colors",
                        to="site_setting.invitationtemplates",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateFontName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="e.g: kh,en,cn", max_length=20
                    ),
                ),
                (
                    "font",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="site_setting.customfont",
                    ),
                ),
                (
                    "invitation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_font_name",
                        to="site_setting.invitationtemplates",
                    ),
                ),
            ],
        ),
    ]
